FROM ubuntu:latest

RUN apt-get update && apt-get install -y bind9

COPY configs/named.conf.options /etc/bind/named.conf.options

EXPOSE 53/tcp
EXPOSE 53/udp

CMD ["named", "-g", "-c", "/etc/bind/named.conf.options"]